set(ZEPHYR_ZMK_DRIVER_ANIMATION_CMAKE_DIR ${CMAKE_CURRENT_LIST_DIR}/zmk-driver-animation)
set(ZEPHYR_ZMK_DRIVER_ANIMATION_KCONFIG   ${CMAKE_CURRENT_LIST_DIR}/zmk-driver-animation/Kconfig)

set(ZEPHYR_ZMK_DRIVER_EXT_POWER_TRANSIENT_CMAKE_DIR ${CMAKE_CURRENT_LIST_DIR}/zmk-driver-ext-power-transient)
set(ZEPHYR_ZMK_DRIVER_EXT_POWER_TRANSIEN_KCONFIG   ${CMAKE_CURRENT_LIST_DIR}/zmk-driver-ext-power-transient/Kconfig)

set(ZEPHYR_ZMK_DRIVER_LED_STRIPNIZE_CMAKE_DIR ${CMAKE_CURRENT_LIST_DIR}/zmk-driver-led-stripnize)
set(ZEPHYR_ZMK_DRIVER_LED_STRIPNIZE_KCONFIG   ${CMAKE_CURRENT_LIST_DIR}/zmk-driver-led-stripnize/Kconfig)

set(ZEPHYR_ZMK_FEATURE_DEFAULT_LAYER_CMAKE_DIR ${CMAKE_CURRENT_LIST_DIR}/zmk-feature-default-layer)
set(ZEPHYR_ZMK_FEATURE_DEFAULT_LAYER_KCONFIG   ${CMAKE_CURRENT_LIST_DIR}/zmk-feature-default-layer/Kconfig)
