manifest:
  remotes:
  projects:
    - name: zmk
      remote: cormoran
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      path: zmk-pmw3610-driver
      # remote: cormoran
      # revision: main
    - name: zmk-feature-default-layer
      path: zmk-feature-default-layer
      # remote: cormoran
      # revision: main
    - name: zmk-driver-animation
      path: zmk-driver-animation
      # remote: cormoran
      # revision: main
    - name: zmk-driver-ext-power-transient
      path: zmk-driver-ext-power-transient
      # remote: cormoran
      # revision: main
    - name: zmk-driver-led-stripnize
      path: zmk-driver-led-stripnize
      # remote: cormoran
      # revision: main
  self:
    path: config
